services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # main edge port
      - "4571:4571"   # optional legacy port
    environment:
      - SERVICES=s3,sqs,dynamodb,lambda,sts,iam,apigateway,cloudformation
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/var/lib/localstack
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock